spring:
  datasource:
    driver-class: org.h2.Driver
    password: ''
    url: jdbc:h2:file:~/playlist
    username: sa
  h2:
    console:
      enable: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operationsSorter: method
    path: /swagger